### ISSUE TITLE
Problem with $make

### ISSUE THREAD

**Issue by SavkeSD** [laurenz/oracle_fdw#372]
When unzip, and try to make, this error is promting
make: *** No targets specified and no makefile found.  Stop.

**Comment by laurenz** [comment]
Since you say `unzip` are you on Windows?

On other operating systems, you have to `cd` into the directory with the software first, where the `Makefile` is.

**Comment by SavkeSD** [comment]
Sry, my bad, working on Windows and on Ubuntu 18.04, and save zip on Ubuntu....

Ok,  now I have problem, when cd into dir, and go $make, following error appears
oracle_utils.c:22:10: fatal error: oci.h: No such file or directory
 #include <oci.h>
          ^~~~~~~
compilation terminated.
<builtin>: recipe for target 'oracle_utils.o' failed

**Comment by laurenz** [comment]
Please read the documentation for the exact installation procedure and the requirements.

Either you didn't install the Oracle header files (the SDK, as they call it), or you didn't set the environment variable `ORACLE_HOME` correctly.

**Comment by SavkeSD** [comment]
It needed 3 things that can move on (Oracle version 11.2.0.4.0):
oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm

I have installed only sqlplus...
Done all of the things. And working with Postgres 12.1.

In PSQL, part create extension oracle_fdw;  return me error
ERROR:  could not load library "/usr/lib/postgresql/12/lib/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

Any clue?

**Comment by laurenz** [comment]
&ast;sigh&ast; I wish you would read the documentation.

> Since the Oracle client shared library is probably not in the standard
> library path, you have to make sure that the PostgreSQL server will be able
> to find it.  How this is done varies from operating system to operating
> system; on Linux you can set LD_LIBRARY_PATH or use `/etc/ld.so.conf`.

**Comment by SavkeSD** [comment]
/etc/postgresql/12/main/environment
also add path for ldconfig
