### ISSUE TITLE
compilation issue with pg 9.6

### ISSUE THREAD

**Issue by fpirotti** [laurenz/oracle_fdw#272]
Upon compilation of code, I get the following error:

    _In file included from oracle_fdw.c:51:0:
    /usr/include/postgresql/9.6/server/optimizer/restrictinfo.h:38:13: note: expected ‘struct List **’ but argument is of type ‘Relids’
     extern void extract_actual_join_clauses(List *restrictinfo_list,
                 ^
    oracle_fdw.c:2905:3: error: too many arguments to function ‘extract_actual_join_clauses’
       extract_actual_join_clauses(extra->restrictlist, joinrel->relids, &joinclauses, &otherclauses);
    In file included from oracle_fdw.c:51:0:
    /usr/include/postgresql/9.6/server/optimizer/restrictinfo.h:38:13: _

**Comment by laurenz** [comment]
You are using 9.6.8 or earlier, right? Upgrading to 9.6.9 or 9.6.10 should fix the problem.

This is one of the rare cases where PostgreSQL's API changed in a minor release.
It must be [this](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=0c141fcaa7dd806752986401b25de8f665ceb3fe) patch that changed the parameter list of `extract_actual_join_clauses`.

I am tempted to leave things the way they are and tell people to upgrade to the latest PostgreSQL point release. All point releases since May 10 have this patch in place, and I think that it is reasonable to expect people to use a recent point release with the latest oracle_fdw.

Adding an `#ifdef` would be the wrong thing, because then you would be able to build with 9.6.8, but oracle_fdw would suddenly start crashing once you upgrade PostgreSQL to 9.6.10, which would be even worse.

But I fear that we will hear about this **a lot** once we make a new release.

The only way to avoid that would be not to use `extract_actual_join_clauses`.

@yamatattsu, what do you think?

**Comment by fpirotti** [comment]
Yep!
PostgreSQL 9.6.7 on x86_64-pc-linux-gnu (Debian 9.6.7-1.pgdg80+1), compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
I will move to a later 9.6 version - but I am afraid that this is a repository version so many people will run into this. 
Thanks!
Francesco

**Comment by laurenz** [comment]
Another issue with that that comes to my mind now is that if someone builds oracle_fdw with 9.6.10, but then uses it with 9.6.8, it will crash just the same.

There is just no way out of that short of not using `extract_actual_join_clauses`...

**Comment by yamatattsu** [comment]
Hmm....
We would be beter to use the function as it is, because to remove or
rewrite extract_actual_join_clauses means that we have to track the
function changes on master continusly.
Instead of that, How about that we write notes regarding binary
compatibility on README?

2018年9月6日(木) 19:36 Laurenz Albe <notifications@github.com>:

**Comment by yamatattsu** [comment]
Hi Laurenz,

I checked two major versions by git log command, and affected versions are
these:
 PG960-PG968
 PG100-PG103

PostgreSQL's API changed in a minor release is touchy problem for us. Oh my
gosh.


2018年9月7日(金) 11:41 Tattsu Yama <yamatattsu@gmail.com>:

**Comment by laurenz** [comment]
I like your idea, Tatsuro.

I have done that, and in addition I have added a check to `_PG_init` that will scream and fail if someone tries to use an oracle_fdw binary with one of the known bad PostgreSQL versions.

I think that's the best we can do.

**Comment by yamatattsu** [comment]
Hi Laurenz,

I'm not sure preprocessor, but how about this fix roughly?

diff --git a/oracle_fdw.c b/oracle_fdw.c
index 061e65e..1151da5 100644
--- a/oracle_fdw.c
+++ b/oracle_fdw.c
@@ -108,8 +108,6 @@
 #endif  /* PG_VERSION_NUM */

 #if PG_VERSION_NUM >= 90600
-#define JOIN_API
-
 /* the useful macro IS_SIMPLE_REL is defined in v10, backport */
 #ifndef IS_SIMPLE_REL
 #define IS_SIMPLE_REL(rel) \
@@ -119,9 +117,13 @@

 /* GetConfigOptionByName has a new signature from 9.6 on */
 #define GetConfigOptionByName(name, varname) GetConfigOptionByName(name,
varname, false)
+#endif  /* PG_VERSION_NUM */
+
+#if PG_VERSION_NUM >= 90609 | PG_VERSION_NUM >= 100004
+#define JOIN_API
 #else
 #undef JOIN_API
-#endif  /* PG_VERSION_NUM */
+#endif


2018年9月7日(金) 16:31 Laurenz Albe <notifications@github.com>:

**Comment by laurenz** [comment]
I think it is better to fail outright than to silently build oracle_fdw without join pushdown support.

That may lead to some hard-to-debug error reports in the future:

- Somebody builds oracle_fdw with 9.6.6.
- Later, PostgreSQL is upgraded to 9.6.10.
- Now joins are not pushed down, and it is impossible to say why without disassembling the binary...

I think it is reasonable to require people to update PostgreSQL, and a clear error message that can lead people to this issue is the best way.

Perhaps we could have a special compile time error message, but this seems like overdoing it.

**Comment by yamatattsu** [comment]
I haven't tested the roughly patch (Idea), sorry.

I intend to only the affected versions can't push down join. But it allows
foreign scan.  If we use this approach, a problem came to my mind is failor
of regression tests because a part of execution plan will be changed.



2018年9月7日(金) 17:33 Tattsu Yama <yamatattsu@gmail.com>:

**Comment by yamatattsu** [comment]
Why I created the roughly patch is:

I may be misunderstanding, but the affected version seemed to make
Oracle_fdw itself unusable by your patch.

I agree that the update of Postgresql is the best way, but I guess that
there is a case which may be difficult. Therefore, I reconsidered that it
would be better to disable join push down by the preprocessor and make it
possible to build. Of course, when using it in a new environment, warning
must be issued as it should be recompiled.

I haven't reached my conclusion...sorry.





2018年9月7日(金) 17:48 Laurenz Albe <notifications@github.com>:
